services:
    user_entity:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ Web\BackendBundle\Entity\User ]

    client_entity:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ Web\BackendBundle\Entity\Client ]

    project_entity:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ Web\BackendBundle\Entity\Project ]

    company_entity:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ Web\BackendBundle\Entity\Company ]

    stage_entity:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ Web\BackendBundle\Entity\Stage ]

    contact_entity:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ Web\BackendBundle\Entity\Contact ]

    position_entity:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ Web\BackendBundle\Entity\Position ]

    industry_entity:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ Web\BackendBundle\Entity\Industry ]

    attachment_entity:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ Web\BackendBundle\Entity\Attachment ]

    sharing_category_entity:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ Web\BackendBundle\Entity\Sharing\Category ]

    contract_entity:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ Web\BackendBundle\Entity\Contract ]

    status_entity:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ Web\BackendBundle\Entity\ContractStatus ]