web_backend_homepage:
    path:     /
    defaults: { _controller: WebBackendBundle:Home:index }

user:
    resource: "@WebBackendBundle/Resources/config/routes/user.yml"
    prefix: /user

contact:
    resource: "@WebBackendBundle/Resources/config/routes/contact.yml"
    prefix: /contact

company:
    resource: "@WebBackendBundle/Resources/config/routes/company.yml"
    prefix: /company

project:
    resource: "@WebBackendBundle/Resources/config/routes/project.yml"
    prefix: /project

position:
    resource: "@WebBackendBundle/Resources/config/routes/position.yml"
    prefix: /position

industry:
    resource: "@WebBackendBundle/Resources/config/routes/industry.yml"
    prefix: /industry

stage:
    resource: "@WebBackendBundle/Resources/config/routes/stage.yml"
    prefix: /stage