web_backend_homepage:
    path:     /
    defaults: { _controller: WebBackendBundle:Home:index }

web_contact_home:
    path: /contact
    defaults: { _controller: WebBackendBundle:Contact:index }

web_company_home:
    path: /company
    defaults: { _controller: WebBackendBundle:Company:index }

property_position:
    path: /property/position
    defaults: { _controller: WebBackendBundle:Property:position }

property_stage:
    path: /property/stage
    defaults: { _controller: WebBackendBundle:Property:stage }

property_industry:
    path: /property/industry
    defaults: { _controller: WebBackendBundle:Property:industry }