web_backend_homepage:
    path:     /
    defaults: { _controller: WebBackendBundle:Home:index }

client:
    resource: "@WebBackendBundle/Resources/config/routes/client.yml"
    prefix: /client

contract:
    resource: "@WebBackendBundle/Resources/config/routes/contract.yml"
    prefix: /contract

user:
    resource: "@WebBackendBundle/Resources/config/routes/user.yml"
    prefix: /user

contact:
    resource: "@WebBackendBundle/Resources/config/routes/contact.yml"
    prefix: /contact

invoice:
    resource: "@WebBackendBundle/Resources/config/routes/invoice.yml"
    prefix: /invoice

company:
    resource: "@WebBackendBundle/Resources/config/routes/company.yml"
    prefix: /company

project:
    resource: "@WebBackendBundle/Resources/config/routes/project.yml"
    prefix: /project

position:
    resource: "@WebBackendBundle/Resources/config/routes/position.yml"
    prefix: /position

industry:
    resource: "@WebBackendBundle/Resources/config/routes/industry.yml"
    prefix: /industry

stage:
    resource: "@WebBackendBundle/Resources/config/routes/stage.yml"
    prefix: /stage

status:
    resource: "@WebBackendBundle/Resources/config/routes/status.yml"
    prefix: /status

sharing:
    resource: "@WebBackendBundle/Resources/config/routes/sharing.yml"
    prefix: /sharing