imports:
    - { resource: factory.yml }

services:
    twig.uri.extension:
        class: Web\BackendBundle\Twig\UriExtension
        arguments: [@request_stack]
        tags:
            - { name: twig.extension }

