imports:
    - { resource: factory.yml }
    - { resource: paginator.yml }

services:
    twig.uri.extension:
        class: Web\BackendBundle\Twig\UriExtension
        arguments: [@request_stack]
        tags:
            - { name: twig.extension }

    twig.char.extension:
        class: Web\BackendBundle\Twig\CharExtension
        tags:
            - { name: twig.extension }

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
           - { name: twig.extension }

    twig.extension.avatar:
        class: Web\BackendBundle\Twig\AvatarExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }

    attachment.manager:
        class: Web\BackendBundle\Attachments\AttachmentsManager
        arguments: [@service_container,@attachment_entity]

    avatar.manager:
        class: Web\BackendBundle\Attachments\AvatarManager
        arguments: [@service_container]