imports:
    - { resource: factory.yml }
    - { resource: paginator.yml }
    - { resource: extensions.yml }
services:

    char.converter:
        class: Web\BackendBundle\Utils\WordsToChars

    color.generator:
        class: Web\BackendBundle\Utils\ColorGenerator

    status.extension:
        class: Web\BackendBundle\Twig\StatusExtension
        tags:
            - { name: twig.extension }

    twig.uri.extension:
        class: Web\BackendBundle\Twig\UriExtension
        arguments: [@request_stack]
        tags:
            - { name: twig.extension }

    twig.char.extension:
        class: Web\BackendBundle\Twig\CharExtension
        tags:
            - { name: twig.extension }

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
           - { name: twig.extension }

    twig.extension.avatar:
        class: Web\BackendBundle\Twig\AvatarExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }

    attachment.manager:
        class: Web\BackendBundle\Attachments\AttachmentsManager
        arguments: [@service_container,@attachment_entity]

    avatar.manager:
        class: Web\BackendBundle\Attachments\AvatarManager
        arguments: [@service_container]

    web.menu_builder:
        class: Web\BackendBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory" , "@service_container"]

    web.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: web.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu