web_frontend:
    resource: "@WebFrontendBundle/Resources/config/routing.yml"
    prefix:   /

web_backend:
    resource: "@WebBackendBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

