security:
    encoders:
        FOS\UserBundle\Model\UserInterface: plaintext

    role_hierarchy:
        ROLE_CONSULTANT: ROLE_USER
        ROLE_PDT: ROLE_CONSULTANT
        ROLE_ADMIN: ROLE_PDT
        ROLE_SUPER_ADMIN: [ROLE_MASTER , ROLE_ADMIN]
        ROLE_MASTER:  ROLE_MASTER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout: true
            anonymous:    true
    access_control:
        # Routes are prefixed by ther user locale.
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: ROLE_MASTER }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[^/]+/admin, role: ROLE_CONSULTANT }
        - { path: ^/[^/]+/, role: ROLE_CONSULTANT }
