user_document:
    path: /
    defaults: { _controller: WebBackendBundle:User:index }

user_contract:
    path: /contract
    defaults: { _controller: WebBackendBundle:User:contract }

user_contract_download:
    path: /{uuid}/download_contract
    defaults: { _controller: WebBackendBundle:User:download }