web_frontend_homepage:
    path:     /
    defaults: { _controller: WebFrontendBundle:Default:index }

home:
    path:     /home
    defaults: { _controller: WebFrontendBundle:Default:home }

info:
    resource: "@WebFrontendBundle/Resources/config/routes/info.yml"
    prefix: /info

account:
    resource: "@WebFrontendBundle/Resources/config/routes/account.yml"
    prefix: /account

