services:
    supply:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ Web\FrontendBundle\Entity\Supply ]

    accountInfo:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ Web\FrontendBundle\Entity\AccountInfo ]